### ISSUE TITLE
怎么改其他学校

### ISSUE THREAD

**Issue by Zjf-lab** [F-19-F/SWU-CpDaily#1]
School_Server_API 啥的怎么找，还需要修改哪些

**Comment by F-19-F** [comment]
首先确认学校登录类型，有ipa和cas登录，这个只实现了没有aes加密的cas登录过程，因为西大就是这种登录过程，这个API可以通过抓包获取，也可以通过app的学校列表获取。总的来说，要改成其他学校只需修改登录和API，其余所有学校是一样的。

**Comment by Zjf-lab** [comment]
> 首先确认学校登录类型，有ipa和cas登录，这个只实现了没有aes加密的cas登录过程，因为西大就是这种登录过程，这个API可以通过抓包获取，也可以通过app的学校列表获取。总的来说，要改成其他学校只需修改登录和API，其余所有学校是一样的。
