### ISSUE TITLE
首次测试成功，再次测试失败

### ISSUE THREAD

**Issue by cloudfly519** [F-19-F/SWU-CpDaily#10]
代码部署好之后第一次单机测试成功
之后单机测试失败，错误代码如下：
START RequestId: 6772af06-2ffa-459d-b803-3727d7b5dbd4

Event RequestId: 6772af06-2ffa-459d-b803-3727d7b5dbd4

2021-10-08 10:52:41 获取代理...

Starting new HTTP connection (1): demo.spiderpy.cn:80

http://demo.spiderpy.cn:80 "GET /get/ HTTP/1.1" 200 181

Starting new HTTP connection (1): demo.spiderpy.cn:80

http://demo.spiderpy.cn:80 "GET /get/ HTTP/1.1" 200 180

Starting new HTTP connection (1): demo.spiderpy.cn:80

http://demo.spiderpy.cn:80 "GET /get/ HTTP/1.1" 200 177

Starting new HTTP connection (1): ip.taobao.com:80

http://ip.taobao.com:80 "GET /outGetIpInfo?ip=59.37.18.243&accessKey=alibaba-inc HTTP/1.1" 301 357

Starting new HTTPS connection (1): ip.taobao.com:443

https://ip.taobao.com:443 "GET /outGetIpInfo?ip=59.37.18.243&accessKey=alibaba-inc HTTP/1.1" 200 None

Starting new HTTP connection (1): 59.37.18.243:3128

http://59.37.18.243:3128 "GET http://baidu.com/ HTTP/1.1" 200 81

2021-10-08 10:52:41 使用代理http://59.37.18.243:3128

Starting new HTTPS connection (1): swu.campusphere.net:443

END RequestId: 6772af06-2ffa-459d-b803-3727d7b5dbd4

Report RequestId: 6772af06-2ffa-459d-b803-3727d7b5dbd4 Duration:3000ms Memory:128MB MemUsage:19.8516MB

**Comment by cloudfly519** [comment]
返回结果 {"errorCode":-1,"errorMessage":"Invoking task timed out after 3 seconds","requestId":"412ecb01-852f-4d0e-bb2a-b7127eb10ad1","statusCode":433}

**Comment by F-19-F** [comment]
网络问题，非代码问题。
