### ISSUE TITLE
出现以下提示 大佬能帮忙找找原因吗

### ISSUE THREAD

**Issue by XinYuJune** [F-19-F/SWU-CpDaily#19]
START RequestId: 172cd23f-8002-44b4-8e39-fe2dea966946

Init Report RequestId: 172cd23f-8002-44b4-8e39-fe2dea966946 Coldstart: 923ms (PullCode: 224ms InitRuntime: 8ms InitFunction: 691ms) Memory: 128MB MemUsage: 12.17MB

ERROR RequestId: 172cd23f-8002-44b4-8e39-fe2dea966946 Result: {"errorCode": -1, "errorMessage": "Traceback (most recent call last):   File "/var/lang/python3/lib/python3.6/urllib/request.py", line 1318, in do_open     encode_chunked=req.has_header('Transfer-encoding'))   File "/var/lang/python3/lib/python3.6/http/client.py", line 1239, in request     self._send_request(method, url, body, headers, encode_chunked)   File "/var/lang/python3/lib/python3.6/http/client.py", line 1285, in _send_request     self.endheaders(body, encode_chunked=encode_chunked)   File "/var/lang/python3/lib/python3.6/http/client.py", line 1234, in endheaders     self._send_output(message_body, encode_chunked=encode_chunked)   File "/var/lang/python3/lib/python3.6/http/client.py", line 1026, in _send_output     self.send(msg)   File "/var/lang/python3/lib/python3.6/http/client.py", line 964, in send     self.connect()   File "/var/lang/python3/lib/python3.6/http/client.py", line 1392, in connect     super().connect()   File "/var/lang/python3/lib/python3.6/http/client.py", line 936, in connect     (self.host,self.port), self.timeout, self.source_address)   File "/var/lang/python3/lib/python3.6/socket.py", line 722, in create_connection     raise err   File "/var/lang/python3/lib/python3.6/socket.py", line 713, in create_connection     sock.connect(sa) ConnectionRefusedError: [Errno 111] Connection refused During handling of the above exception, another exception occurred: Traceback (most recent call last):   File "/var/runtime/python3/bootstrap.py", line 133, in init_handler     func_handler = get_func_handler(file.rsplit(".", 1)[0], func)   File "/var/runtime/python3/bootstrap.py", line 159, in get_func_handler     mod = imp.load_module(mname, *imp.find_module(mname))   File "/var/lang/python3/lib/python3.6/imp.py", line 234, in load_module     return load_source(name, filename, file)   File "/var/lang/python3/lib/python3.6/imp.py", line 172, in load_source     module = _load(spec)   File "<frozen importlib._bootstrap>", line 675, in _load   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked   File "<frozen importlib._bootstrap_external>", line 678, in exec_module   File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed   File "/var/user/index.py", line 26, in <module>     res=urllib.request.urlopen(req)   File "/var/lang/python3/lib/python3.6/urllib/request.py", line 223, in urlopen     return opener.open(url, data, timeout)   File "/var/lang/python3/lib/python3.6/urllib/request.py", line 526, in open     response = self._open(req, data)   File "/var/lang/python3/lib/python3.6/urllib/request.py", line 544, in _open     '_open', req)   File "/var/lang/python3/lib/python3.6/urllib/request.py", line 504, in _call_chain     result = func(*args)   File "/var/lang/python3/lib/python3.6/urllib/request.py", line 1361, in https_open     context=self._context, check_hostname=self._check_hostname)   File "/var/lang/python3/lib/python3.6/urllib/request.py", line 1320, in do_open     raise URLError(err) urllib.error.URLError: <urlopen error [Errno 111] Connection refused>", "statusCode": 443}

END RequestId: 172cd23f-8002-44b4-8e39-fe2dea966946

Report RequestId: 172cd23f-8002-44b4-8e39-fe2dea966946 Duration: 0ms Memory: 128MB MemUsage: 12.17MB

START RequestId:172cd23f-8002-44b4-8e39-fe2dea966946

ERROR RequestId:172cd23f-8002-44b4-8e39-fe2dea966946 Result:{"errorCode":-1,"errorMessage":"Traceback (most recent call last):\n  File \"/var/lang/python3/lib/python3.6/urllib/request.py\", line 1318, in do_open\n    encode_chunked=req.has_header('Transfer-encoding'))\n  File \"/var/lang/python3/lib/python3.6/http/client.py\", line 1239, in request\n    self._send_request(method, url, body, headers, encode_chunked)\n  File \"/var/lang/python3/lib/python3.6/http/client.py\", line 1285, in _send_request\n    self.endheaders(body, encode_chunked=encode_chunked)\n  File \"/var/lang/python3/lib/python3.6/http/client.py\", line 1234, in endheaders\n    self._send_output(message_body, encode_chunked=encode_chunked)\n  File \"/var/lang/python3/lib/python3.6/http/client.py\", line 1026, in _send_output\n    self.send(msg)\n  File \"/var/lang/python3/lib/python3.6/http/client.py\", line 964, in send\n    self.connect()\n  File \"/var/lang/python3/lib/python3.6/http/client.py\", line 1392, in connect\n    super().connect()\n  File \"/var/lang/python3/lib/python3.6/http/client.py\", line 936, in connect\n    (self.host,self.port), self.timeout, self.source_address)\n  File \"/var/lang/python3/lib/python3.6/socket.py\", line 722, in create_connection\n    raise err\n  File \"/var/lang/python3/lib/python3.6/socket.py\", line 713, in create_connection\n    sock.connect(sa)\nConnectionRefusedError: [Errno 111] Connection refused\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/var/runtime/python3/bootstrap.py\", line 133, in init_handler\n    func_handler = get_func_handler(file.rsplit(\".\", 1)[0], func)\n  File \"/var/runtime/python3/bootstrap.py\", line 159, in get_func_handler\n    mod = imp.load_module(mname, *imp.find_module(mname))\n  File \"/var/lang/python3/lib/python3.6/imp.py\", line 234, in load_module\n    return load_source(name, filename, file)\n  File \"/var/lang/python3/lib/python3.6/imp.py\", line 172, in load_source\n    module = _load(spec)\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 675, in _load\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 655, in _load_unlocked\n  File \"\u003cfrozen importlib._bootstrap_external\u003e\", line 678, in exec_module\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 205, in _call_with_frames_removed\n  File \"/var/user/index.py\", line 26, in \u003cmodule\u003e\n    res=urllib.request.urlopen(req)\n  File \"/var/lang/python3/lib/python3.6/urllib/request.py\", line 223, in urlopen\n    return opener.open(url, data, timeout)\n  File \"/var/lang/python3/lib/python3.6/urllib/request.py\", line 526, in open\n    response = self._open(req, data)\n  File \"/var/lang/python3/lib/python3.6/urllib/request.py\", line 544, in _open\n    '_open', req)\n  File \"/var/lang/python3/lib/python3.6/urllib/request.py\", line 504, in _call_chain\n    result = func(*args)\n  File \"/var/lang/python3/lib/python3.6/urllib/request.py\", line 1361, in https_open\n    context=self._context, check_hostname=self._check_hostname)\n  File \"/var/lang/python3/lib/python3.6/urllib/request.py\", line 1320, in do_open\n    raise URLError(err)\nurllib.error.URLError: \u003curlopen error [Errno 111] Connection refused\u003e","statusCode":443}

END RequestId:172cd23f-8002-44b4-8e39-fe2dea966946

Report RequestId:172cd23f-8002-44b4-8e39-fe2dea966946 Duration:0ms Memory:128MB MemUsage:0.000000MB

**Comment by F-19-F** [comment]
代码拉取时出错了

**Comment by XinYuJune** [comment]
> 代码拉取时出错了

谢谢作者大佬，平安夜快乐
