### ISSUE TITLE
这两天是出问题吗

### ISSUE THREAD

**Issue by way0922** [F-19-F/SWU-CpDaily#2]
昨天开始签到，查寝失败，开始时是超时，后面我改了以后变成学校服务出问题，是接口改了吗

**Comment by F-19-F** [comment]
是的，学校登陆服务器目前屏蔽非学校公网的ip，并且就算你是学校公网的ip，也登陆不进去。
![IMG_20210518_084745](https://user-images.githubusercontent.com/58457605/118573844-dd9dc500-b7b5-11eb-9f6b-cf793be6c5d9.jpg)
![IMG_20210518_084721](https://user-images.githubusercontent.com/58457605/118573849-decef200-b7b5-11eb-9a2e-d7e5595c281f.jpg)

**Comment by F-19-F** [comment]
但是接口的url是没有变的

**Comment by way0922** [comment]
还可以解决吗

**Comment by F-19-F** [comment]
> 还可以解决吗

今晚push新版本，密码换成修改后的密码即可。
