### ISSUE TITLE
导入Gitee出错

### ISSUE THREAD

**Issue by HuOneNumber** [F-19-F/SWU-CpDaily#3]
将仓库导入自己的gitee中，然后再云函数将index.py 中res=urllib.request.urlopen(url='https://raw.githubusercontent.com/F-19-F/SWU-CpDaily/master/index.py')，改为自己gitee的仓库index.py的地址，测试云函数却出错，请问该如何解决呢

**Comment by F-19-F** [comment]
码云会封代码，你看下码云那个链接是否能正常打开？

**Comment by HuOneNumber** [comment]
应该是被封了的意思吧urllib.error.HTTPError: HTTP Error 403: Forbidden","statusCode":443}，谢谢，已经很好用了，就主要有时会调用失败，感觉是github的代码没拉取下来的锅，所以才想试试码云哈哈哈

**Comment by F-19-F** [comment]
更新为github镜像，测试比直接从github拉稳定
