### ISSUE TITLE
可否解决新版版本低的错误，非贵校

### ISSUE THREAD

**Issue by qingcheng123** [F-19-F/SWU-CpDaily#4]

**Comment by F-19-F** [comment]
版本低一般是DES密钥不对哦

**Comment by qingcheng123** [comment]
密钥是对的，博主怎么联系你，我私发你看下------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年6月19日(星期六) 晚上9:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [F-19-F/SWU-CpDaily] 可否解决新版版本低的错误，非贵校 (#4)

**Comment by F-19-F** [comment]
不方便提供........
