### ISSUE TITLE
大佬怎末适配其他学校呢？

### ISSUE THREAD

**Issue by MY214000** [F-19-F/SWU-CpDaily#5]
如题⬆⬆⬆

**Comment by F-19-F** [comment]
只要你实现登录过程拿到cookie就适配好了，代码中的签到类和查寝类都是通用的

**Comment by MY214000** [comment]
感谢！！！我去尝试尝试




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "F-19-F/SWU-CpDaily"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月2日(星期一) 晚上9:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [F-19-F/SWU-CpDaily] 大佬怎末适配其他学校呢？ (#5)





 
只要你实现登录过程拿到cookie就适配好了，代码中的签到类和查寝类都是通用的
