### ISSUE TITLE
获取lt失败

### ISSUE THREAD

**Issue by Jeekate** [F-19-F/SWU-CpDaily#7]
本地windows + python3.9.5 环境运行正常，可以签到、查寝发送调试信息，但是上腾讯云就一直返回“获取lt失败”。
在服务器手动执行函数收到的调试信息包含了前一次失败的信息，消息累加起来了。。但是本地运行就不会出现任何问题。。是服务器端设置有问题吗

**Comment by F-19-F** [comment]
lt获取失败看明天怎么样，腾讯云函数有缓存变量的机制，所以消息会累加起来。

**Comment by CherryCherries** [comment]
我也遇到了获取lt失败的问题。。有什么解决方法嘛？
