### ISSUE TITLE
今天突然提示“UserCode”错误

### ISSUE THREAD

**Issue by XinYuJune** [F-19-F/SWU-CpDaily#8]
{"errorCode":-1,"errorMessage":"UserCodeError","statusCode":443}
以上是日志输入的具体错误，是不是被拉入黑名单了
（根据大佬您的代码魔改了一下 除了学校代码不同 其他全部一样）

**Comment by F-19-F** [comment]
详细一点，看下是哪一部分出错

**Comment by XS30** [comment]
ERROR RequestId:fcafb90a-ec20-4e89-bd80-b13a7b2ff1d4 Result:{"errorCode":-1,"errorMessage":"UserCodeError","statusCode":443}

Report RequestId:fcafb90a-ec20-4e89-bd80-b13a7b2ff1d4 Duration:0ms Memory:128MB MemUsage:0.000000MB

**Comment by XS30** [comment]
今天我根据您的方法进行测试，发现也出现了类似的错误，同西南大学

**Comment by XinYuJune** [comment]
> [详细一点，看下是哪一部分出错]
![image](https://user-images.githubusercontent.com/74338675/135116330-4f47a0b8-66f6-428a-8727-03a85f380be7.png)
这是具体测试的日志截图 麻烦大佬您看一下

**Comment by XinYuJune** [comment]
![image](https://user-images.githubusercontent.com/74338675/135116498-1c88f82d-7738-4b1f-b770-b8b53796f403.png)
具体代码截图 麻烦大佬您看一下

**Comment by F-19-F** [comment]
腾讯云函数的问题

**Comment by XinYuJune** [comment]
> 可能是腾讯云函数的问题，代码没拉取。试试换香港节点的服务器

好的我去试试看

**Comment by XS30** [comment]
> 可能是腾讯云函数的问题，代码没取。

测试了，香港节点可以

**Comment by CherryCherries** [comment]
感谢

**Comment by PieceZhang** [comment]
香港节点可以
