### ISSUE TITLE
适配其它院校

### ISSUE THREAD

**Issue by azi666** [F-19-F/SWU-CpDaily#9]
![image](https://user-images.githubusercontent.com/57692681/135945748-5d1b9907-9d2d-4cc7-8316-4dd3db89142e.png)
你好，作者 我想适配我们学校的，但是提示这个，可以请教下么

**Comment by F-19-F** [comment]
先要确定你学校是ipa登录还是cas登录

**Comment by azi666** [comment]
是cas登录

**Comment by azi666** [comment]
https://xxx.campusphere.net/portal/Flogin

**Comment by F-19-F** [comment]
用Login-Utils里CAS-aes那个登录试试。。。。。。。。
